"""create initial tables

Revision ID: d4561c7722b4
Revises: 
Create Date: 2026-06-05 22:01:44.518275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4561c7722b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE IF NOT EXISTS wallet_index_seq START WITH 1 INCREMENT BY 1")
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('holder_did', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('credential', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('active', 'revoked', 'expired', name='credentialstatus'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.Integer(), nullable=True),
    sa.Column('revoke_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_credential_id'), 'credentials', ['credential_id'], unique=True)
    op.create_index(op.f('ix_credentials_holder_did'), 'credentials', ['holder_did'], unique=False)
    op.create_index(op.f('ix_credentials_id'), 'credentials', ['id'], unique=False)
    op.create_index(op.f('ix_credentials_revoked_by'), 'credentials', ['revoked_by'], unique=False)
    op.create_table('dids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('did', sa.String(), nullable=False),
    sa.Column('ethereum_address', sa.String(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=True),
    sa.Column('document_hash', sa.String(), nullable=True),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dids_did'), 'dids', ['did'], unique=True)
    op.create_index(op.f('ix_dids_id'), 'dids', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('wallet_index', sa.Integer(), nullable=False),
    sa.Column('eth_address', sa.String(length=42), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', 'student', 'teacher', name='user_role_enum'), server_default='user', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eth_address'),
    sa.UniqueConstraint('wallet_index')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.execute("DROP SEQUENCE IF EXISTS wallet_index_seq")
    op.drop_index(op.f('ix_dids_id'), table_name='dids')
    op.drop_index(op.f('ix_dids_did'), table_name='dids')
    op.drop_table('dids')
    op.drop_index(op.f('ix_credentials_revoked_by'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_holder_did'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_credential_id'), table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###
